### ISSUE TITLE
Archer A7 V5 setup failed

### ISSUE THREAD

**Issue by chunjiw** [AlexandrErohin/home-assistant-tplink-router#10]
Hi, I tried this on Archer A7 V5, firmware version 1.1.2 with no luck. The router does not require a username to log in, so I keep "admin" unchanged; after entering password and hit "Submit", it says connection successful momentarily then back on the integration page, it says "setup failed".

Thank you for this integration all the same!

**Comment by chunjiw** [comment]
Here is the error log. I think it is the same as #9 

```
2023-12-13 16:42:24.837 ERROR (SyncWorker_8) [custom_components.tplink_router] 'model'
2023-12-13 16:42:24.837 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.1.1 for tplink_router
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2023-12-13 16:44:04.662 ERROR (SyncWorker_5) [custom_components.tplink_router] 'model'
2023-12-13 16:44:04.663 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.1.1 for tplink_router
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2023-12-13 16:44:30.579 ERROR (SyncWorker_7) [custom_components.tplink_router] 'model'
2023-12-13 16:44:30.580 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.1.1 for tplink_router
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AlexandrErohin** [comment]
Since I don’t have the opportunity to test on this version of the router, you can download the [client](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and check which requests are incorrect for this router.

**Comment by AlexandrErohin** [comment]
Since I don’t have the opportunity to test on this version of the router, you can download the [client](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and check which requests are incorrect for this router.

**Comment by AlexandrErohin** [comment]
I have added more logs for errors.
@chunjiw Could you reinstall it and check the logs again?

**Comment by AlexandrErohin** [comment]
@chunjiw this error was fixed in v1.2.3. Please reinstall and check again

**Comment by chunjiw** [comment]
I reinstalled and this time it works, and I am now able to track my phone. Thank you for this awesome work!

**Comment by AlexandrErohin** [comment]
@chunjiw Could you try please the new version and let me know how it goes?
