### ISSUE TITLE
Unable to add integeration for TP-link Router TL-7DR7260

### ISSUE THREAD

**Issue by leihuashan** [AlexandrErohin/home-assistant-tplink-router#101]
**Describe the bug**
You need to use web encrypted password instead. Check the documentation!
Even you input the encrypted password ,it is still show the tip

**Logs**
Add also all relevant logs from **Settings->System->Logs**.

**Additional Information (please complete the following information)**
 - Router Hardware Version: TL-7DR7260
 - Router Firmware Version: 1.0.18
 - Home Assistant Version: 2024.10.2
 - TP-Link Router Integration Component Version: v1.18.0

**Comment by AlexandrErohin** [comment]
Hi
Your router is not supported - Would be great if you could add support for your router by creating PR with new class that extends https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L19

**Comment by moriont** [comment]
> Hi. Could you try the latest integration version?

Hello, i have tried latest version which is v2.8.3 with TL-7DR7260, and get error as below:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 48, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tplink_router/coordinator.py", line 58, in request
    data = callback()
  File "/config/custom_components/tplink_router/__init__.py", line 43, in callback
    firm = client.get_firmware()
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/wdr.py", line 243, in get_firmware
    self._updateStatus()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/wdr.py", line 298, in _updateStatus
    self._parseSummary(raw)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/wdr.py", line 542, in _parseSummary
    tFirm = data["script0"][6]
            ~~~~^^^^^^^^^^^
KeyError: 'script0'
