### ISSUE TITLE
Unable to add integration for M4R v2.0

### ISSUE THREAD

**Issue by pHiR0** [AlexandrErohin/home-assistant-tplink-router#105]
**Describe the bug**
Cannot set up the integration with an deco M4R v2.0.

When I enter the URL and Password it indicates that it has been configured correctly, but then in the integration it shows the following:

No devices or entities
Could not be configured: 
Check logs

**Logs**
```
2024-10-26 20:37:56.198 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.151.194 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 43, in callback
    stat = client.get_status()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 591, in get_status
    IPv4Address(ip),
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 1319, in __init__
    self._ip = self._ip_int_from_string(addr_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 1206, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'UNKNOWN'
```

**Additional Information (please complete the following information)**
 - Router Hardware Version: M4R (2.0)
 - Router Firmware Version: 1.6.2 Build 20240308 Rel. 55841
 - Home Assistant Version:  2024.10.4
 - TP-Link Router Integration Component Version: 1.18.0

**Comment by AlexandrErohin** [comment]
@pHiR0 Fixed. Please try version 1.19.0

**Comment by AlexandrErohin** [comment]
Would be great if you could give a star to the repo :) Thanks
