### ISSUE TITLE
Archer C7 V5 Error setting up entry

### ISSUE THREAD

**Issue by idle1975** [AlexandrErohin/home-assistant-tplink-router#11]
Thank you for your work on the integration.
Since the router's IP is 192.168.5.1, I tried logging in with all the combinations I could think of.
Currently, my log looks like the following.

The router model is: Archer C7 V5, firmware 1.2.1 

'Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 14:24:03 (1 occurrences)
Last logged: 14:24:03

Error setting up entry 192.168.5.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
'

**Comment by AlexandrErohin** [comment]
Since I don’t have the opportunity to test on this version of the router, you can download the [client](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and check which requests are incorrect for this router.

**Comment by AlexandrErohin** [comment]
I have added more logs for errors.
Could you reinstall it and check the logs again?

**Comment by idle1975** [comment]
In version 1.3.1, the addition went correctly. Thanks!

**Comment by AlexandrErohin** [comment]
@idle1975 the latest integration version is v1.2.3
Does it works for your Archer C7 V5 ?

**Comment by idle1975** [comment]
Yes sorry, Of course, this is about version 1.2.3. Seems to work OK on Archer C7 v5.0. Only memory used is N/A at the moment.

**Comment by AlexandrErohin** [comment]
It looks like your router doesnt supports memory sensor. Since I don’t have the opportunity to test on this version of the router, you can download the [client](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and check what parameters in the response from admin/status?form=all
