### ISSUE TITLE
BE800 - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/firmware?form=upgrade - Response

### ISSUE THREAD

**Issue by zhunhung** [AlexandrErohin/home-assistant-tplink-router#114]
**Describe the bug**

After logging in via HomeAssistant UI, I get this error immediately.

**Logs**
Add also all relevant logs from **Settings->System->Logs**.

![Screenshot 2024-11-07 at 6 06 46 PM](https://github.com/user-attachments/assets/d0d35967-3f1a-4371-9134-22fe16db378d)
![Screenshot 2024-11-07 at 6 06 59 PM](https://github.com/user-attachments/assets/ba8bfd76-2501-4d28-8640-e6a9e805ea32)

**Additional Information (please complete the following information)**
 - Router Hardware Version:
Hardware Version:
Archer BE800 v1.0
 - Router Firmware Version:
  Firmware Version:
1.1.6 Build 20240808 rel.26673(5347)
 - Home Assistant Version: 
Core
2024.10.3
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241002.3
 - TP-Link Router Integration Component Version: 2.0.0

**Comment by AlexandrErohin** [comment]
Could you post the full error here?

**Comment by zhunhung** [comment]
```
2024-11-07 18:06:27.661 ERROR (SyncWorker_3) [custom_components.tplink_router] TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["<full password>","010001"],"mode":"router","username":""}}
2024-11-07 18:06:28.443 ERROR (SyncWorker_5) [custom_components.tplink_router] TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/firmware?form=upgrade - Response 
2024-11-07 18:06:28.447 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.0.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 42, in callback
    firm = client.get_firmware()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 316, in get_firmware
    data = self.request(self._url_firmware, 'operation=read')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 112, in request
    raise ClientError(error)
tplinkrouterc6u.exception.ClientError: TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/firmware?form=upgrade - Response 
2024-11-07 18:06:39.193 ERROR (MainThread) 
```

Here you go!

**Comment by AlexandrErohin** [comment]
Your router dosnt provide firmware info. It is strange as Archer BE800 v1.0 was tested OK here https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/34

**Comment by zhunhung** [comment]
Yup, thats why I'm not too sure what's wrong. It does provide the firmware info though, when I logged into the web UI of the router, the api call is successful.

![Screenshot 2024-11-07 at 7 14 34 PM](https://github.com/user-attachments/assets/4fe51452-20aa-453d-91a2-06d2ab8b908f)

When I try to use this package tplinkrouterc6u and run a separate python script, it returns {"data": ""} which is the same issue I raised.

**Comment by AlexandrErohin** [comment]
Do you have the latest Router Firmware Version ?
When you use tplinkrouterc6u could you call get_status() ? does it work?

**Comment by zhunhung** [comment]
Yup, it is the latest version. I cant call get_status() as well:
```
try:
    router.authorize()  # authorizing
    # Get status info - returns Status
    status = router.get_status()
```
Output:
```
True
http://tplinkwifi.net/cgi-bin/luci/;stok=cd64513952fbfaac1a3511a62829c7ed/admin/status?form=all&operation=read 
True
...
tplinkrouterc6u.exception.ClientError: TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/status?form=all&operation=read - Response 
```

**Comment by AlexandrErohin** [comment]
Do you use router local password or password from TP-LINK ID?

**Comment by zhunhung** [comment]
I used local password, I verified by using the password for this:
![Screenshot 2024-11-07 at 7 40 10 PM](https://github.com/user-attachments/assets/331bb808-6028-4ade-bacc-bc343ca10a2c)


```
router = TplinkRouterProvider.get_client('http://192.168.0.1', <local password>')
```

If I input the wrong password, I will get this error:
```
Exception: Not authorised
```

**Comment by AlexandrErohin** [comment]
It is better to ask help @nicandris as he has this router and has tested this client for BE800

**Comment by nicandris** [comment]
I'm not using hassio, can you run this? https://gist.github.com/nicandris/c822b68f56c4efffff3eb53f37ab584d#file-be800-tplinkrouterc6u-py-L92

i just tried it and it can fetch the firmware just fine. (you dont really need to run the entire script, you can run `router = TplinkRouterProvider.get_client(args.url, args.credentials)` and then `firmware = router.get_firmware()`

**Comment by zhunhung** [comment]
Thanks @nicandris!

router = TplinkRouterProvider.get_client(args.url, args.credentials) and then firmware = router.get_firmware()

Running get_firmware() gives the same error:
```
tplinkrouterc6u.exception.ClientError: TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/firmware?form=upgrade - Response 
```

**Comment by thegeekybeng** [comment]
On that note, the same thing is happening for my Archer BE 805,  it is a relief to know that likely is not an isolated issue.

**Comment by AlexandrErohin** [comment]
Do you have something that uses your password to login to the router constantly ? Like mobile APP

**Comment by zhunhung** [comment]
> Do you have something that uses your password to login to the router constantly ? Like mobile APP

I just tried to log out of the router in the Tether app and reload the integration. The same error persists :/

**Comment by kennethcyh** [comment]
Want to flag this as the same issue I'm also having, with the BE805:
```
Firmware Version:
1.0.12 Build 20240819 rel.66201(5347)
Hardware Version:
Archer BE805 v1.0
```

**Comment by shadehv** [comment]
Confirming that this issue still exists on the **Archer BE800** as of **May 2025**.

### 🔧 Test Environment:
- **Router Model:** Archer BE800
- **Firmware Version:** 1.2.3 Build 20250314 rel.45415 (latest as of May 2025)
- **Home Assistant OS:** 2024.5
- **Integration Source:** HACS (v2.8.0)
- **SSL Verification:** Disabled in config
- **Password:** Alphanumeric only (no special characters)

### 🧪 Behavior:
- Setup fails with the same traceback:

- Visiting `https://192.168.0.1/admin/firmware?form=upgrade` directly in browser returns:


### ✅ Steps Already Taken:
- Firmware confirmed up-to-date
- Simplified password (alphanumeric only)
- SSL disabled
- Tested manually in browser — endpoint is clearly gone
- Log error matches exactly what's described in original issue

---

Would be great to know if any progress is underway or if there's a way the community can help identify the new endpoints or contribute packet captures for newer BE800 firmware versions.

Let me know if you need debug logs, HAR traces, or anything else!

Thanks for keeping this awesome integration alive.

**Comment by shadehv** [comment]
Thank you for your reply.

🧩 Additional info for Archer BE800 support (May 2025):

After debugging with integration logging and HAR inspection, I’ve confirmed that the Archer BE800 (firmware 1.2.3 Build 20250314 rel.45415) does **not** expose `/admin/firmware?form=upgrade` or any related legacy endpoints expected by the integration.

Instead, the router uses:
POST https://redacted-ip/cgi-bin/luci/;stok=<session_token>/api/misystem/firmware_upgrade


These are **authenticated**, session-based API calls using the `stok=` model (similar to a stripped-down LuCI variant used in OpenWRT-based UIs).

Captured valid response characteristics:
- `Content-Type: application/json`
- HTTP Status: `200 OK`
- Endpoint path: `/cgi-bin/luci/;stok=...`

🎯 Request method: `POST`  
🧾 Headers and payload follow typical LuCI-style session authentication behavior.

---

📁 I’ve attached a fully sanitized `.har` capture here for dev inspection:  
👉[BE800.har.txt](https://github.com/user-attachments/files/20236776/BE800.har.txt)

I'm happy to test any patches or provide more detailed traces if needed. A fallback client class (e.g., `TPLinkLucixClient`) or conditional API detection might allow BE800 support to be restored cleanly.

Thanks for maintaining this awesome integration!

**Comment by AlexandrErohin** [comment]
@shadehv Hi.
It looks like your router has different API
1) Could you run this code and post the result
```
from tplinkrouterc6u import TplinkRouter
from logging import Logger

router = TplinkRouter('http://192.168.0.1','your_password','admin', Logger('test'))
router.authorize()
print(router.request('api/misystem/firmware_upgrade', 'operation=load'))
```
2) There is more request to the router - like
- admin/status?form=all
- admin/dhcps?form=reservatio
- admin/dhcps?form=client
I think these urls also doesnt work with your router

**Comment by shadehv** [comment]
Hi Alexandr,

Thanks for the follow-up!

🧪 I ran the test script you suggested with:

from tplinkrouterc6u import TplinkRouter
from logging import Logger

router = TplinkRouter('http://192.168.0.1', 'my_password', 'admin', Logger('test'))
router.authorize()
print(router.request('api/misystem/firmware_upgrade', 'operation=load'))

Unfortunately, it throws a JSONDecodeError because the router returns an empty or invalid response. The authorize() method doesn't succeed — BE800 doesn’t support this legacy login flow.

📌 Confirmed Behavior (Archer BE800)
My router (BE800, firmware 1.2.3 Build 20250314 rel.45415) uses a different API model:

* Login happens via a POST to:

  https://192.168.0.1/cgi-bin/luci/;stok=/login?form=login

* Payload is not username/password. It requires:

  * sign=... (encrypted blob)
  * data=... (encrypted credentials)
  * No stok is returned from that call — it's extracted later by frontend JS.

* Session is stored via a cookie like:
  Set-Cookie: sysauth=...; path=/cgi-bin/luci

* API calls require the session cookie and use endpoints like:
  /cgi-bin/luci/;stok=<token>/api/misystem/firmware_upgrade

Also, these endpoints do not exist:

 /admin/status?form=all
 /admin/dhcps?form=client

Confirmed via HAR trace and browser inspection.

Would you be open to adding a TPLinkBE800Client class or alternate backend handler for this newer auth flow? I'm happy to help supply:

Working HAR captures

Live login + token flow

Firmware/version identifiers

Sample output

Let me know if you'd like to collaborate on this — happy to help!

Thanks again for maintaining this project 🙌

**Comment by AlexandrErohin** [comment]
@shadehv As I dont have this router - would be great if you add the support for your router by adding new class TPLinkBE800Client to https://github.com/AlexandrErohin/TP-Link-Archer-C6U. You may use examples for other routers -  https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/CONTRIBUTING.md

**Comment by EnricoBara** [comment]
If it may help I started getting this error today, when I updated the TL-WR1502x to 1.2.10 (from 1.1) and I think they changed something in the local login interface since I don't see the username text box anymore. This firmware cannot be downgraded so i can't check it. I also tried setting up a https connection and I get this message. 

![Image](https://github.com/user-attachments/assets/f03288aa-9458-44bd-8ed7-d411e812d5f1)

**Comment by EnricoBara** [comment]
Update: I temporarily solved following [this](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/220#issuecomment-3269188945)

**Comment by AlexandrErohin** [comment]
Please try the latest version of the integration

**Comment by banister4728** [comment]
> Please try the latest version of the integration

I have the exact same problem using 2.14.1. The password is correct as I get a unauthorised error if I change the password.

Hardware Version: Archer BE805 v1.20
Firmware Version: 1.2.2 Build 20250424 rel.45837(5347)

```
from tplinkrouterc6u import TplinkRouter
from logging import Logger

router = TplinkRouter('http://192.168.1.1','password','admin', Logger('test'))
router.authorize()
router.get_status()
```

```
Traceback (most recent call last):
  File "TP-Link-Archer-C6U/test.py", line 6, in <module>
    router.get_status()
  File "TP-Link-Archer-C6U/tplinkrouterc6u/client/c6u.py", line 288, in get_status
    data = self.request('admin/status?form=all&operation=read', 'operation=read')
  File "TP-Link-Archer-C6U/tplinkrouterc6u/client/c6u.py", line 74, in request
    raise ClientError(error)
tplinkrouterc6u.common.exception.ClientError: TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/status?form=all&operation=read - Response
```

**Comment by banister4728** [comment]
> > Please try the latest version of the integration
> 
> I have the exact same problem using 2.14.1. The password is correct as I get a unauthorised error if I change the password.
> 
> Hardware Version: Archer BE805 v1.20 Firmware Version: 1.2.2 Build 20250424 rel.45837(5347)
> 
> ```
> from tplinkrouterc6u import TplinkRouter
> from logging import Logger
> 
> router = TplinkRouter('http://192.168.1.1','password','admin', Logger('test'))
> router.authorize()
> router.get_status()
> ```
> 
> ```
> Traceback (most recent call last):
>   File "TP-Link-Archer-C6U/test.py", line 6, in <module>
>     router.get_status()
>   File "TP-Link-Archer-C6U/tplinkrouterc6u/client/c6u.py", line 288, in get_status
>     data = self.request('admin/status?form=all&operation=read', 'operation=read')
>   File "TP-Link-Archer-C6U/tplinkrouterc6u/client/c6u.py", line 74, in request
>     raise ClientError(error)
> tplinkrouterc6u.common.exception.ClientError: TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/status?form=all&operation=read - Response
> ```

Upon further investigation, I found out that the request to https://192.168.1.1/cgi-bin/luci/;stok=stokstring/admin/firmware?form=upgrade uses data/sign as the initial /cgi-bin/luci/;stok=/login. I tried modding the get_firmware() in TplinkRouter to use the _prepare_data() in TplinkEncryption but still didn't get any data in the reply.

**Comment by AlexandrErohin** [comment]
Please try the latest version of the integration
