### ISSUE TITLE
Unable to install the module

### ISSUE THREAD

**Issue by Didde3866** [AlexandrErohin/home-assistant-tplink-router#117]
**Describe the bug**
I can’t install the module
**Logs**
This is the error I got: HTTPConnectionPool(host='192.168.2.1', port=80): Max retries exceeded with url: /cgi/getParm?_=1731481308157 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64a94530>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Additional Information (please complete the following information)**
 - Router Hardware Version: Model M9 plus - firmware 1.6.4
 - Router Firmware Version: 3.8.69
 - Home Assistant Version: 2024.11.1
 - TP-Link Router Integration Component Version: 2.0.1

**Comment by AlexandrErohin** [comment]
Could you run this python code and post the output here
```
from tplinkrouterc6u import TPLinkDecoClient
from logging import Logger

router = TPLinkDecoClient('http://192.168.0.1', 'you_plain_password', logger=Logger('test'))

router.authorize()
firmware = router.get_firmware()
print(firmware.firmware_version)

status = router.get_status()
print(status.wired_total)
```

**Comment by AlexandrErohin** [comment]
You may try the new version 2.1.0

**Comment by Didde3866** [comment]
> You may try the new version 2.1.0

2.1 doen’t appaers in bacs

**Comment by Didde3866** [comment]
> You may try the new version 2.1.0

Now I got this error “ HTTPConnectionPool(host='192.168.2.1', port=80): Max retries exceeded with url: /cgi-bin/luci/;stok=/login?form=keys&operation=read (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7841c320>: Failed to establish a new connection: [Errno 111] Connection refused'))”
Even if I restart the router to kill all conections with it.

**Comment by AlexandrErohin** [comment]
Have you run the code?

**Comment by azizle** [comment]
can you specify where to run this code?

**Comment by AlexandrErohin** [comment]
@azizle You may run it on your PC connected to your router M9

**Comment by azizle** [comment]
this is what i got:
```
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\tplinkrouterc6u\client\c6u.py", line 150, in _request_pwd
    args = data[self._data_block]['password']
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\Downloads\ghntghn.py", line 6, in <module>
    router.authorize()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\tplinkrouterc6u\client\c6u.py", line 99, in authorize
    self._request_pwd()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\tplinkrouterc6u\client\c6u.py", line 160, in _request_pwd
    raise ClientException(error)
tplinkrouterc6u.common.exception.ClientException: TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["D1E79FF1...FD","010001"],"mode":"router","username":""
```

**Comment by AlexandrErohin** [comment]
@azizle Do you have the latest firmware for your router? It looks like your router uses old API
Try this code
```
from tplinkrouterc6u import TplinkRouter
from logging import Logger

router = TplinkRouter('http://192.168.0.1', 'you_plain_password', logger=Logger('test'))

router.authorize()
firmware = router.get_firmware()
print(firmware.firmware_version)

status = router.get_status()
print(status.wired_total)
```

**Comment by azizle** [comment]
This code works and gave an expected response (6). The router is an AX72 v1.0 on the latest firmware.

**Comment by AlexandrErohin** [comment]
@azizle What the error when you add the integration?

**Comment by azizle** [comment]
``` HTTPConnectionPool(host='192.168.0.1', port=80): Max retries exceeded with url: /cgi-bin/luci/;stok=/login?form=keys&operation=read (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f40a29d90>, 'Connection to 192.168.0.1 timed out. (connect timeout=30)')) ```

**Comment by AlexandrErohin** [comment]
@azizle Could you test this code?
```
from tplinkrouterc6u import TplinkRouterProvider
from logging import Logger

router = TplinkRouterProvider.get_client('your_router_host', 'you_plain_password', logger=Logger('test'))

router.authorize()
firmware = router.get_firmware()
print(firmware.firmware_version)

status = router.get_status()
print(status.wired_total)

```

**Comment by azizle** [comment]
this also works, same output as before

**Comment by AlexandrErohin** [comment]
@azizle Thats mean your HA cannot connect to your router. As this code is the same what the integration uses to connect to the router.  The error ConnectTimeoutError means that the problem on the network layer

**Comment by azizle** [comment]
I see, HA is working fine wired to the router though so I have no clue why it's not working

**Comment by SleepInfinity** [comment]
Nevermind, I had activated local management for specific devices and added only my PC and my phone. 
Now that I've added Home Assistant, I can activate the integration.
