### ISSUE TITLE
Unable to install package tplinkrouterc6u==5.3.0

### ISSUE THREAD

**Issue by milkucika** [AlexandrErohin/home-assistant-tplink-router#122]
**Describe the bug**
Hello. I have only a few HACS components all of them working except this. I'm stucked at the install phase. Using HA via GUI.
Core 2024.10.4
Frontend 20241002.4
Am I missed an install step?

**Logs**
Add also all relevant logs from **Settings->System->Logs**.
Logger: homeassistant.util.package
Source: util/package.py:150
Unable to install package tplinkrouterc6u==5.3.0: error: failed to create file `/snap/home-assistant-snap/637/.lock` Caused by: Permission denied

Logger: aiohttp.server
Source: /snap/home-assistant-snap/637/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 3:51:37 PM (1 occurrences)
Last logged: 3:51:37 PM

Error handling request
Traceback (most recent call last):
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1312, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1499, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2964, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2941, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/snap/home-assistant-snap/637/lib/python3.12/site-packages/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for tplink_router not found: ['tplinkrouterc6u==5.3.0'].

**Additional Information (please complete the following information)**
Firmware Version: 1.3.3 Build 20240628 rel.37017(4555) Hardware Version: Archer AX55 v1.0

**Comment by AlexandrErohin** [comment]
Hi!
The main error is - Unable to install package tplinkrouterc6u==5.3.0: error: failed to create file /snap/home-assistant-snap/637/.lock Caused by: Permission denied
The problem in HACS or HA
Here is a similar problem - https://github.com/home-assistant/core/issues/128214
