### ISSUE TITLE
home assistant 2024.12.x breaks integration 

### ISSUE THREAD

**Issue by RMHogervorst** [AlexandrErohin/home-assistant-tplink-router#126]
**Describe the bug**
I upgraded my home assistant docker image to 2024.12.3 and now this integration stopped working.

**Logs**
Add also all relevant logs from **Settings->System->Logs**.
```
2024-12-15 13:34:16.193 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tplink_router': Unable to import component: No module named 'tplinkrouterc6u'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/tplink_router/__init__.py", line 12, in <module>
    from tplinkrouterc6u import TPLinkMRClient
ModuleNotFoundError: No module named 'tplinkrouterc6u'
```

**Additional Information (please complete the following information)**

version | core-2024.12.3
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 5.15.0-126-generic
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4945
Installed Version | 2.0.1
Stage | running
Available Repositories | 1546
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 15
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 6, 2024 at 11:19
-- | --
current_recorder_run | December 15, 2024 at 13:34
estimated_db_size | 1330.48 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

 - Router Hardware Version: P9
 - Router Firmware Version: 1.2.1 build 20240716 Rel. 60900
 - Home Assistant Version:  2024.12.3
 - TP-Link Router Integration Component Version: 2.2.0

**Comment by RMHogervorst** [comment]
https://community.home-assistant.io/t/python-libraries-missing-in-2024-12-0/805633

**Comment by AlexandrErohin** [comment]
@RMHogervorst Could you try to reinstall the integration?

**Comment by RMHogervorst** [comment]
Yes, this works!

**Comment by AlexandrErohin** [comment]
@RMHogervorst Would be great if you could give a star to the repo :) Thanks
