### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by pgarnek** [AlexandrErohin/home-assistant-tplink-router#14]
i see in logs same error occurs > 1200 times.
my router is Archer C6 V2.0
```
Logger: homeassistant
Source: custom_components/tplink_router/sensor.py:67
Integration: TP-Link Router ([documentation](https://github.com/AlexandrErohin/home-assistant-tplink-router), [issues](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues))
First occurred: 12:47:06 (1207 occurrences)
Last logged: 23:37:15

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/tplink_router/sensor.py", line 115, in _handle_coordinator_update
    self._attr_native_value = self.entity_description.value(self.coordinator.status)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/sensor.py", line 67, in <lambda>
    value=lambda status: (status.cpu_usage * 100) if status.cpu_usage >= 0 else 0,
                                                     ^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by AlexandrErohin** [comment]
@pgarnek fixed in v1.2.5
