### ISSUE TITLE
Cannot add AX11000 any more after update.

### ISSUE THREAD

**Issue by Paul1865** [AlexandrErohin/home-assistant-tplink-router#28]
**Describe the bug**
After the last update, I had to add my router again, but I can't get it added due to some error. 

**Logs**

2024-01-31 21:30:07.122 ERROR (SyncWorker_6) [custom_components.tplink_router] TplinkRouter Integration Exception - 'wan_macaddr'
2024-01-31 21:30:07.122 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.2.200 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 56, in async_setup_entry
    coordinator = TPLinkRouterCoordinator(hass, device, entry.data[CONF_SCAN_INTERVAL], info, _LOGGER, entry.entry_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 25, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable


**Additional Information (please complete the following information)**
Firmware versie: 1.3.4 Build 20230906 rel.74809(4555)
Hardware versie: Archer AX11000 v1.0

**Comment by AlexandrErohin** [comment]
@Paul1865 Thanks for the bug info
I have fixed it. Please reinstall version v1.5.1 and try again. Let me know the result

**Comment by Paul1865** [comment]
Yessss! 🎉 
Thanks a lot man.
