### ISSUE TITLE
Log Error: "AttributeError: 'NoneType' object has no attribute 'devices'"

### ISSUE THREAD

**Issue by tekHudson** [AlexandrErohin/home-assistant-tplink-router#32]
**Describe the bug**
found error when checking logs for login 

**Logs**
```
AttributeError: 'NoneType' object has no attribute 'devices'
2024-02-15 10:32:11.496 ERROR (SyncWorker_2) [custom_components.tplink_router] TplinkRouter Integration Exception - HTTPConnectionPool(host='192.168.0.1', port=80): Read timed out. (read timeout=10)
2024-02-15 10:32:11.497 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/tplink_router/device_tracker.py", line 28, in coordinator_updated
    update_items(coordinator, async_add_entities, tracked)
  File "/config/custom_components/tplink_router/device_tracker.py", line 43, in update_items
    for device in coordinator.status.devices:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Additional Information (please complete the following information)**
 - Firmware: 1.2.1 Build 20220714 rel.75573(5553)
 - Hardware: Archer A7 v5.0
 - Home Assistant Software  
   - Core 2024.2.1
   - Supervisor 2024.01.1
   - Operating System 11.5
   - Frontend 20240207.1
 - TP-Link Router Integration Component Version:

**Comment by tekHudson** [comment]
Can't confirm in the version upgrade from 1.6 to 1.7 I no longer see the air in the logs
