### ISSUE TITLE
UnicodeDecodeError when setting up device

### ISSUE THREAD

**Issue by fraserdominicdavid** [AlexandrErohin/home-assistant-tplink-router#53]
**Describe the bug**
The integration throws a `UnicodeDecodeError` and cannot setup the device in Home Assistant. I never had this issue before, and it all worked fine with my [TL-MR150](https://www.tp-link.com/en/home-networking/3g-4g-router/tl-mr150/) router.

<details>

<summary><b>Logs</b></summary>

```python
Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 9:11:47 AM (1 occurrences)
Last logged: 9:11:47 AM

Error setting up entry http://192.168.2.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 43, in callback
    stat = client.get_status()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 842, in get_status
    _, values = self.req_act(acts)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 1019, in req_act
    (code, response) = self._request(url, data_str=data, encrypt=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 1224, in _request
    return r.status_code, self._encryption.aes_decrypt(r.text)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/encryption.py", line 105, in aes_decrypt
    return unpad(response, 16, 'pkcs7').decode('utf8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1067: invalid start byte
```
</details>

**Additional Information (please complete the following information)**
 - Router Hardware Version: TL-MR150 v2 00000001
 - Router Firmware Version: 1.1.0.0.9.1 Build 210803 Rel.55933n
 - Home Assistant Version: 2024.4.4
 - TP-Link Router Integration Component Version: 1.13.2

**Comment by AlexandrErohin** [comment]
Hi!
Could you try to restart your router?

**Comment by fraserdominicdavid** [comment]
Hi, that seemed to fix the issue when I restarted the router and reloaded the integration just now. However, I think it's important to note that I did try that before, and it didn't work exactly like what happened just now.

**Comment by AlexandrErohin** [comment]
@fraserdominicdavid Great that it works for you!
Would be great if you could give a start for this repo. Thanks!

**Comment by fraserdominicdavid** [comment]
Hi @AlexandrErohin, I am encountering this error again, even after trying the following to troubleshoot:

1. Restarted router
2. Restarted Home Assistant
3. Uninstalled the integration, restart Home Assistant, installed integration, restart Home Assistant, add router

Even after trying all of these, the integration still throws the `UnicodeDecodeError` even though it was working fine before.

<details>

<summary><b>Logs</b></summary>

```python
Logger: homeassistant.config_entries
Source: config_entries.py:751
First occurred: 11:43:04 AM (1 occurrences)
Last logged: 11:43:04 AM

Error setting up entry http://192.168.2.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 48, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 58, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 44, in callback
    stat = client.get_status()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/mr.py", line 155, in get_status
    _, values = self.req_act(acts)
                ~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/mr.py", line 347, in req_act
    (code, response) = self._request(url, data_str=data, encrypt=True)
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/mr.py", line 561, in _request
    return r.status_code, self._encryption.aes_decrypt(r.text)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/common/encryption.py", line 123, in aes_decrypt
    return unpad(response, 16, 'pkcs7').decode('utf8')
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 1385: invalid start byte
```
</details>

**Additional Information (please complete the following information)**
 - Router Hardware Version: TL-MR150 v2 00000001
 - Router Firmware Version: 1.1.0.0.9.1 Build 210803 Rel.55933n
 - Home Assistant Version: 2025.4.4
 - TP-Link Router Integration Component Version: 2.8.0
