### ISSUE TITLE
Can't turn on/off Guest Wifi on Deco x50

### ISSUE THREAD

**Issue by bchevreau** [AlexandrErohin/home-assistant-tplink-router#73]
**Describe the bug**
Unable to turn on or off the Guest Wifi on Deco x50 router. I have a feeling it is because in the newer version of the Deco App, both 2.4G and 5G are turning on simultaneously (only one toggle for both bands) but I am unsure how to verify as the error message isn't very explicit.

Note: the reporting works fine: if I turn it off via the app, I can see it turn off in the configuration toggles in Home Assistant. But I cannot initiate the action: toggling on/off throws errors.

**Logs**
`Failed to perform the action switch/turn_off. TplinkRouter - TPLinkDecoClient - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/wireless?form=wlan - Response Vr94vjuSaW9DP1/oebKjrgh2+8B31/Fmthzzajam5phEe/USIfMe9k4ILFprCVqLxPgKzhrGpDuwn9qdWTMUuoFEVFUUp430zApRdj/QN6ThsAuoUxWf8cRxasx+vyBy1NRMnld5buqY/0nOHmWzPRaIzd22TOgizmeiKxzY7oB5LCsUIP0fi+Z/KYZpvCuLoJjdIMHBwcYRyE/BkubB6Wc9Fnp9FRVFNpd65kkkfMCRUBD8srtblD+un4UBvtPE8VPbxVFQ5t2qUHVBA3lSZX2W5X88+M1YkVHFUudZrFW6Fjo8ghLrDqtwdl7EwkR1rnSGJglbn9rvTaUii7lXLDJuPfQziURsA5amd2+qzJE=`

**Additional Information (please complete the following information)**
 - Router Hardware Version: Deco x50
 - Router Firmware Version: 1.2.6 Build 20240328 Rel. 74284
 - Home Assistant Version: latest
 - TP-Link Router Integration Component Version: latest

![image](https://github.com/user-attachments/assets/9bb53df7-9915-4b58-8838-1a0d714245c9)

**Comment by sebabordon** [comment]
I have an XE75 Pro (v1 and v2) and it seems that it doesn't work as well. I can see status but not disable nor enable the guest wifi

**Comment by bchevreau** [comment]
@AlexandrErohin Anything I can help with for that issue? I'm happy to provide logs or go thru some debugging with you to find a way to fix those if ever. The main problem I would assume seems to be that the command sends separate commands for 2.4G and 5G whereas the DECO x50 / X60 and similar have a single switch for both of those.

**Comment by AlexandrErohin** [comment]
@bchevreau 
Hi.
As I dont have Deco router - could you use this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and play with wifi switch?
You may test like this
```
from tplinkrouterc6u import TPLinkDecoClient
from logging import Logger
from json import dumps

client = TPLinkDecoClient('192.168.0.1', 'yourPassword', logger=Logger('test'))
client.authorize()
print(self.request('admin/wireless?form=wlan', dumps({'operation': 'write', 'params': {'band2_4': {'host': {'enable': True}}}})))
```

**Comment by sebabordon** [comment]
I tried the script, with the following output (I had to install it in debian using pipx with ---install-deps)
I also tried another code in the site and the problem it seems that is not authorizing. 

Traceback (most recent call last):
  File "/home/seba/.local/pipx/venvs/./tplink2.py", line 9, in <module>
    print(self.request('admin/wireless?form=wlan', dumps({'operation': 'write', 'params': {'band2_4': {'host': {'enable': True}}}})))
          ^^^^
NameError: name 'self' is not defined

**Comment by AlexandrErohin** [comment]
@bchevreau 
Try this
```
from tplinkrouterc6u import TPLinkDecoClient
from logging import Logger
from json import dumps

client = TPLinkDecoClient('192.168.0.1', 'yourPassword', logger=Logger('test'))
client.authorize()
print(client.request('admin/wireless?form=wlan', dumps({'operation': 'write', 'params': {'band2_4': {'host': {'enable': True}}}})))
```

**Comment by sebabordon** [comment]
@AlexandrErohin tried it... after some seconds, I receive the following

`TplinkRouter - TPLinkDecoClient - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/wireless?form=wlan - Response sF+6iVSeFc/MAG8eSxcQTQH3e0at3b4qlvP5iRy8a25KxabbUqFhUV/Zw+T7BEnwbpm2kfH15Yq+sm5J++Dsk+BXIUvR0ANyMjUXSdIiwSESgkrPBvYRe9CeTMfeOWGEaTyjHKwxaFtKjJjo6tgEBCwMYza9owMzGL2+pP3zrXptM6lx0EMo0ozRNPWT/n6U22zwzTFxVsTwao8K7xYHdYYe66dn+0qX2ULYpeVulGThdzWiqEArtDzasumrGZCVFzlenchM395+W/jyo3lYtbNcX6/la2WvwhSD6AkhmpRHTmMmDca1CBQxvd8gKGnFRE8knoNVp+/xKTTmEqEDXz7eU1F8VB+g2vQDLXwQFLk=
Traceback (most recent call last):
  File "/home/seba/.local/pipx/venvs/tplink3.py", line 7, in <module>
    print(client.request('admin/wireless?form=wlan', dumps({'operation': 'write', 'params': {'band2_4': {'host': {'enable': True}}}})))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seba/.local/pipx/venvs/tplinkrouterc6u/lib/python3.11/site-packages/tplinkrouterc6u/client.py", line 111, in request
    raise ClientError(error)
tplinkrouterc6u.exception.ClientError: TplinkRouter - TPLinkDecoClient - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/wireless?form=wlan - Response sF+6iVSeFc/MAG8eSxcQTQH3e0at3b4qlvP5iRy8a25KxabbUqFhUV/Zw+T7BEnwbpm2kfH15Yq+sm5J++Dsk+BXIUvR0ANyMjUXSdIiwSESgkrPBvYRe9CeTMfeOWGEaTyjHKwxaFtKjJjo6tgEBCwMYza9owMzGL2+pP3zrXptM6lx0EMo0ozRNPWT/n6U22zwzTFxVsTwao8K7xYHdYYe66dn+0qX2ULYpeVulGThdzWiqEArtDzasumrGZCVFzlenchM395+W/jyo3lYtbNcX6/la2WvwhSD6AkhmpRHTmMmDca1CBQxvd8gKGnFRE8knoNVp+/xKTTmEqEDXz7eU1F8VB+g2vQDLXwQFLk=`

**Comment by ConnorHayward** [comment]
A few extra things I have noticed when looking into it:
The Deco App for the XE75 groups channels, there are not seperate toggles for 2.4 and 5. You must toggle the entire guest network on, then toggle the individual channels.

I looked into the TP Link API, and it mentions taking logs when logged into the router through the browser. At least when I looked around, I did not see a way to toggle networks on or off via the browser, so I was unable to scrape the command needed.

**Comment by spektus** [comment]
Any updates or breakthroughs? I'm facing the same issue. I can see the Wi-Fi status, but I'm unable to toggle it. I tried disabling the 5 GHz guest Wi-Fi and using only 2.4 GHz, but the issue persists. I also tested with 2.4 GHz disabled and only 5 GHz enabled, but the result is the same.

**Comment by Antrac1t** [comment]
question is if plugin "simulate" mobile app or web app, because thru web you are able to see guest status (ON/OFF) but you cant change status, but thru deco app you can change it

**Comment by AlexandrErohin** [comment]
Im afraid, TP-LINK restricted the WIFI network control for some Deco devices via web gui. There is no more Enable/disable guest\host wifi network for them. Only what can be controlled - is Enable/disable wifi network (guest+host simultaneously)

**Comment by arturotolinski** [comment]
Same wall here, on a different model and a much newer firmware — and I managed to decrypt that "garbled encrypted response", so here is what it actually says.

**Why it looks like garbage:** on a failed wireless write the router answers with **HTTP 500 and a body that is AES-encrypted but *not* wrapped in the usual `{"data": "…"}` envelope** — it is the raw base64 ciphertext. Any client that only decrypts `response["data"]` will see nothing useful. Decrypt the whole body with the current session key and it becomes readable:

```
Failed to execute call dispatcher target for entry '/admin/wireless'.
The called action terminated with an exception:
?:0: attempt to index global 'mode' (a nil value)
stack traceback:
	[C]: in function 'assert'
	?: in function 'dispatch'
	?: in function <?:218>
```

So the request never reaches the wireless code — the router's own Lua dispatcher dereferences a nil global `mode` and aborts. This is a firmware fault, not a malformed request.

**What I ruled out** (every variant below returned that exact same traceback):

| variant | result |
|---|---|
| single flag, i.e. what `DecoClient.set_wifi` sends: `{"operation":"write","params":{"band6":{"guest":{"enable":false}}}}` | HTTP 500, same trace |
| full network object, echoing back every field the preceding read returned | HTTP 500, same trace |
| all bands at once | HTTP 500, same trace |
| `operation` moved into the query string (`?form=wlan&operation=write`) | HTTP 500, same trace |
| `mode` added to the query string, to the body, and inside `params` | HTTP 500, same trace |
| `Referer` + `Origin` headers added (as `tplinkrouterc6u` does) | HTTP 500, same trace |
| `operation: "set"`, `operation: "wlan_write"`, `operation` omitted | `{"error_code":1,"msg":"no such callback"}`, HTTP 200 |

That last row matters: the dispatcher clearly distinguishes a non-existent operation (`no such callback`, HTTP 200) from `write`, which exists and then blows up inside. Session and permissions are also out — a `{"operation":"read"}` on the very same `form=wlan` immediately before and immediately after each failed write returns the full configuration, in the same session.

I also enumerated the forms under `/admin/wireless`: only `wlan` and `power` exist. There is no alternative write endpoint to fall back to, which also implies the router's own web UI has to use this same broken path.

**My device:** Deco XE75 Pro, firmware `1.3.1 Build 20251023 Rel. 47884`, region DE, running as an **access point** — `/admin/device?form=mode` returns `{"region":{"device":"DE"},"workmode":"FAP","sysmode":"AP"}`. Since @bchevreau saw this on an X50 with `1.2.6 Build 20240328`, this is neither model-specific nor a recent regression.

**One thing worth collecting from anyone else who hits this:** the output of `/admin/device?form=mode`. My only remaining hypothesis is that the nil `mode` global is reached on a code path that is only taken in AP mode — if everyone reporting the failure turns out to be running as an access point, that is the pattern. I cannot test it myself; switching a live installation to router mode is not something I can do to check a hunch.

Consistent with the original report that changes made in the Deco app do work: the app talks to the TP-Link cloud, so it never touches this dispatcher.

**Suggestion for the library:** decrypting non-200 bodies costs a few lines and turns this from "obscured encrypted response" into an actionable message. Roughly:

```python
if response.status_code != 200:
    try:
        detail = self._decrypt(response.text.strip())   # raw body, no {"data": …} envelope
    except Exception:
        detail = response.text[:200]
    raise ClientError(f"HTTP {response.status_code}: {detail}")
```

Happy to run further probes against this router if anything specific would help.

**Comment by arturotolinski** [comment]
Correction to my comment above: I wrote that nobody had decrypted that response. That was wrong, and I apologise for the misattribution — @adrianvillagra had already done it in #354 (June 2026, closed as a duplicate of this issue, so it is easy to miss). That report is more thorough than mine and deserves to be read first.

Worth pulling one detail of theirs up into this thread, because their firmware does not strip the Lua paths the way mine does:

```
/usr/lib/lua/luci/dispatcher.lua:498: Failed to execute call dispatcher target for entry '/admin/wireless'.
The called action terminated with an exception:
...luci-apps-1.0/dist/controller/admin/wireless.lua:84: attempt to index global 'mode' (a nil value)
```

So the crash has a name and address: **`controller/admin/wireless.lua`, line 84**. On my unit the same traceback comes back as `?:0:`.

What my measurements add on top of #354:

- **Another firmware line and another region.** Theirs: XE75 (US) v1.0, `1.4.5 Build 20241129`. Mine: **XE75 Pro (EU/DE), `1.3.1 Build 20251023 Rel. 47884`**. Together with the X50 on `1.2.6 Build 20240328` in the original report, that is three firmware lines, three model variants and two regions.
- **It is not only the guest network.** Host networks fail identically — `band2_4/host` and `band5_1/host` produce the same traceback, so this blocks all radio control, not just guest WiFi.
- **`Referer` and `Origin` headers make no difference** (adding both, as `tplinkrouterc6u` does for other models, changes nothing; a read in the same session with the same headers still succeeds).
- **There is no alternative endpoint to fall back to.** Enumerating forms under `/admin/wireless` on my firmware yields exactly two that exist: `wlan` and `power`. Everything else answers `no such callback`.

**A question for @adrianvillagra, if you still have the unit:** what does `/admin/device?form=mode` return for you? Mine reports `{"region":{"device":"DE"},"workmode":"FAP","sysmode":"AP"}` — it runs as an access point, and my one remaining hypothesis was that the nil `mode` global is only reached on an AP-mode code path. If your unit is in router mode and still crashes, that hypothesis is dead.

For what it is worth, your observation that the **web UI shows the guest network as read-only** points at a different and more plausible story: that TP-Link moved wireless configuration to the app and left the LuCI controller half-removed, with `wireless.lua:84` referencing a global that nothing initialises any more. That would explain why the failure spans firmware lines, models and regions, and why the app keeps working while every local path is dead.

@AlexandrErohin — of your three options in #354, the third is cheap and would have saved two people a fair amount of work: decrypting non-200 bodies before raising. The response on failure is raw AES base64 with no `{"data": …}` envelope, so `response.json()` fails and the useful message is discarded. A few lines around the existing decryptor turn "obscured encrypted response" into the traceback above.
