### ISSUE TITLE
Archer C60 v2.0 and TL-WA1201 3.0 - any chance of adding support?

### ISSUE THREAD

**Issue by snigehere** [AlexandrErohin/home-assistant-tplink-router#9]
Hi - thanks for the integration - 
I have an Archer C60 v2.0 Firmware 2.0.0 Build 20161206 rel.60287
and a TL-WA1201 3.0 Firmware 1.10.32 Build 221020 Rel.61052n(4555)

I am looking for some kind of integration that I could use to access them for device tracking - is it possible to add this to the integration?  Can I provide any information / detail to help?

I tried to connect both and got errors so guess there is no supported so far.... 

This is the error from the Archer C60

2023-12-13 23:55:42.549 ERROR (SyncWorker_2) [custom_components.tplink_router.config_flow] can only concatenate str (not "dict") to str
2023-12-13 23:55:42.656 ERROR (SyncWorker_3) [custom_components.tplink_router] can only concatenate str (not "dict") to str
2023-12-13 23:55:42.658 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.1.254 for tplink_router
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
self.firmware = info[0]
~~~~^^^


And this the error detail for the TL-WA1201 3.0

2023-12-14 00:08:17.668 ERROR (SyncWorker_5) [custom_components.tplink_router.config_flow] Extra data: line 1 column 2 (char 1)
2023-12-14 00:08:17.677 ERROR (SyncWorker_4) [custom_components.tplink_router] Extra data: line 1 column 2 (char 1)
2023-12-14 00:08:17.678 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.1.2 for tplink_router
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
self.firmware = info[0]
~~~~^^^
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable

Thanks

**Comment by AlexandrErohin** [comment]
Since I don’t have the opportunity to test on this version of the router, you can download the [client](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and check which requests are incorrect for this router.

**Comment by AlexandrErohin** [comment]
I have added more logs for errors.
@snigehere  Could you reinstall it and check the logs again?

**Comment by snigehere** [comment]
Hi - Thanks - I deleted my integration components and redownloaded from hacs - version shows as 1.2.3

I re-added the integration and entered the detail for logon but can't get past the configuration page now - I get the below error and the configuration page resets to default

2023-12-14 23:50:18.616 ERROR (MainThread) [custom_components.tplink_router.config_flow] TplinkRouter Integration Exception - Unkown error for pwd: {"errorcode":"no such callback","success":false}

![Snap14](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/104912027/f538e87a-4cde-49bb-a67e-9b3eb9f44844)
![Snap15](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/104912027/7f750fe2-9b02-4c80-bdcc-308b0dd52900)

**Comment by AlexandrErohin** [comment]
Your router has different api. Since I don’t have the opportunity to test on this version of the router, you can download the [client](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and check which requests are incorrect for this router.

**Comment by snigehere** [comment]
Thanks - That will take me a while as I will need to do some learning first .. I will get back when I find out any answers

**Comment by AlexandrErohin** [comment]
@snigehere Please try new version - As TP-link Archer C1200 v2.0 support with different login process was added - your router may also be supported now

**Comment by snigehere** [comment]
Hi - Thanks for your action .. unfortunately neither work

Previously the Archer C60 had to be rebooted after trying the integration as I could not log back on manually .. This time I got the message "You need to use web encrypted password instead. Check the documentation!" so when to try and the router seemed to think it did not have a password set so prompted for a new one so I could not follow the encrypted password steps.  I need to reboot it at the end of the day.

The WA1201 gave the same "You need to use web encrypted password instead. Check the documentation!" message so I followed the steps  
document.getElementById("login-password").value;
responded with 
VM219:1 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at <anonymous>:1:42

**Comment by StLukesLivestream** [comment]
Ok - archer c60 rebooted ... 
Ahead of integration setup I was able to get the web encrypted password from the console ... I used this and this time got the error  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

I tried again with the standard password just to make sure and still got the "You need to use web encrypted password instead. Check the documentation!" message ... I guess its progress as no lockup on the interface this time.

**Comment by AlexandrErohin** [comment]
Thats mean your router has different API

Would be great if you could add support for your router by creating PR with new class that extends https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L16

**Comment by AlexandrErohin** [comment]
Hi! Could you try the HA integration latest version please?

**Comment by StLukesLivestream** [comment]
Hello @AlexandrErohin Thanks for continuing to develop this integration

I am very please to confirm I was able to install and configure the integration.  It didn't work with the text password but using your very clear instructions I extracted the web password and successfully logged in via the integration.

I can now see devices and entities and will explore it further next week.

Again many thanks for your help and support

**Comment by snigehere** [comment]
Closing this enhancement request as the router is now supported

**Comment by AlexandrErohin** [comment]
@snigehere Have you tried also TL-WA1201 ?

**Comment by AlexandrErohin** [comment]
Would be great if you could give a star to the repo :) Thanks

**Comment by StLukesLivestream** [comment]
> [@snigehere](https://github.com/snigehere) Have you tried also TL-WA1201 ?

I am now using the TL-WA1201 in switch mode but I was able to logon and and create the integration - but it showed an error which I would expect as its not in router mode
http://192.168.1.2
No devices or entities
Failed to set up:
Check the logs

The log shows
2025-03-14 18:52:01.355 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.1.2 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 48, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tplink_router/coordinator.py", line 58, in request
    data = callback()
  File "/config/custom_components/tplink_router/__init__.py", line 44, in callback
    stat = client.get_status()
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/c80.py", line 164, in get_status
    wifi_status = {key: extract_value(data_blocks[request], "bEnable ") == '1'
                                      ~~~~~~~~~~~^^^^^^^^^
KeyError: '33|1,9,0'

**Comment by AlexandrErohin** [comment]
@StLukesLivestream Hi. I have fixed the error. Could you try the latest integration version?

**Comment by StLukesLivestream** [comment]
Hello @AlexandrErohin 

Thank you again for your help - I downloaded 2.7 and have added the other device and its showing connected devices

**Comment by AlexandrErohin** [comment]
@StLukesLivestream What is the hardware version of this device?

**Comment by StLukesLivestream** [comment]
The integration tells me 
Firmware: 1.10.40 Build 240715 Rel.34137n(4555)
Hardware: TL-WA1201 3.0
